name: Update Profile README

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab
  schedule:
    - cron: '0 15 * * *' # Runs every day at 15:00 UTC = 12:00 BRT

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate AI Quote and Update README
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python .github/scripts/generate_content.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✨ feat: Update profile with fresh AI insight"
          file_pattern: 'README.md'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          commit_author: 'Ricardo <62864640+rickkk856@users.noreply.github.com>'
          
      - name: Verify update
        run: |
          echo "✅ Profile updated successfully!"
          echo "Last commit:"
          git log -1 --oneline
